version: "3.8"

services:
  db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "${PORT}:3000"

volumes:
  db_data:
    name: mariadb-data
